# https://cloud.google.com/appengine/docs/standard/go/config/appref
runtime: go122
service: feed

# The sha1_sum for the favicon for some reason has underscores in it, which
# then fails the CreateVersion request checks "does not match the pattern..."
# handlers:
# - url: /favicon\.ico
#   static_files: static/favicon.ico
#   upload: static/favicon\.ico

instance_class: F1

inbound_services:
- warmup

automatic_scaling:
  target_cpu_utilization: 0.55

  target_throughput_utilization: 0.60
  # max_concurrent_requests: 10

  max_pending_latency: 300ms
  # min_pending_latency: 0ms

  max_idle_instances: 1
  min_idle_instances: 0

  max_instances: 10

env_variables:
  # Template
  HEADLINE: "Welcome to PlaneChat"
  TEXT_COLOR: "blue"

  # Performance
  CONN_POOL_SIZE: 10
  MAX_THREADS: 10

  # Configs
  SELF_DOCS: 3
  FEED_DOCS: 5

  # Features
  INCLUDE_FOLLOWERS: true 
  TXN_RETRY_STRAT: "none"