# https://cloud.google.com/appengine/docs/standard/go/config/appref
runtime: go115
service: feed

handlers:
# - url: /favicon\.ico
#   static_files: static/favicon.ico
#   upload: static/favicon\.ico

instance_class: F2

inbound_services:
- warmup

automatic_scaling:
  target_cpu_utilization: 0.60
  target_throughput_utilization: 0.60
  max_concurrent_requests: 10
  max_pending_latency: 500ms

env_variables:
  # Template
  HEADLINE: "Welcome to PlaneChat"
  TEXT_COLOR: "blue"

  # Performance
  CONN_POOL_SIZE: 5
  MAX_THREADS: 5

  # Configs
  SELF_DOCS: 3
  FEED_DOCS: 5

  # Features
  INCLUDE_FOLLOWERS: true 
  TXN_RETRY_STRAT: "none"