# https://cloud.google.com/appengine/docs/standard/go/config/appref
runtime: go122
service: user

instance_class: F1

inbound_services:
- warmup

automatic_scaling:
  target_cpu_utilization: 0.5

  target_throughput_utilization: 0.60
  max_concurrent_requests: 10

  max_pending_latency: 3.8s
  min_pending_latency: 0.0s

  max_idle_instances: 0
  min_idle_instances: 0

  max_instances: 10
env_variables:
  # Performance
  CONN_POOL_SIZE: 10
  MAX_THREADS: 10

  TXN_RETRY_STRAT: "none"